In [2]:
import pandas as pd
import duckdb       #SQL
import os
from pathlib import Path #automatically handles file paths across different operating systems
import xlrd         #EXCEL
import pyreadstat   #SPSS

# VDEM Data

In [3]:
data_folder = Path(r"../data/raw/VDEM")
vdem_file_path = data_folder /"V-Dem-CY-Full+Others-v16.csv"

In [4]:
vdem_df = pd.read_csv(vdem_file_path, nrows=3)
print(vdem_df.columns.tolist())

['country_name', 'country_text_id', 'country_id', 'year', 'historical_date', 'project', 'historical', 'histname', 'codingstart', 'codingend', 'codingstart_contemp', 'codingend_contemp', 'codingstart_hist', 'codingend_hist', 'gapstart1', 'gapstart2', 'gapstart3', 'gapend1', 'gapend2', 'gapend3', 'gap_index', 'COWcode', 'v2x_polyarchy', 'v2x_polyarchy_codelow', 'v2x_polyarchy_codehigh', 'v2x_polyarchy_sd', 'v2x_libdem', 'v2x_libdem_codelow', 'v2x_libdem_codehigh', 'v2x_libdem_sd', 'v2x_partipdem', 'v2x_partipdem_codelow', 'v2x_partipdem_codehigh', 'v2x_partipdem_sd', 'v2x_delibdem', 'v2x_delibdem_codelow', 'v2x_delibdem_codehigh', 'v2x_delibdem_sd', 'v2x_egaldem', 'v2x_egaldem_codelow', 'v2x_egaldem_codehigh', 'v2x_egaldem_sd', 'v2x_api', 'v2x_api_codelow', 'v2x_api_codehigh', 'v2x_api_sd', 'v2x_mpi', 'v2x_mpi_codelow', 'v2x_mpi_codehigh', 'v2x_mpi_sd', 'v2x_freexp_altinf', 'v2x_freexp_altinf_codelow', 'v2x_freexp_altinf_codehigh', 'v2x_freexp_altinf_sd', 'v2x_frassoc_thick', 'v2x_frassoc_thick_codelow', 'v2x_frassoc_thick_codehigh', 'v2x_frassoc_thick_sd', 'v2x_suffr', 'v2xel_frefair', 'v2xel_frefair_codelow', 'v2xel_frefair_codehigh', 'v2xel_frefair_sd', 'v2x_elecoff', 'v2x_liberal', 'v2x_liberal_codelow', 'v2x_liberal_codehigh', 'v2x_liberal_sd', 'v2xcl_rol', 'v2xcl_rol_codelow', 'v2xcl_rol_codehigh', 'v2xcl_rol_sd', 'v2x_jucon', 'v2x_jucon_codelow', 'v2x_jucon_codehigh', 'v2x_jucon_sd', 'v2xlg_legcon', 'v2xlg_legcon_codelow', 'v2xlg_legcon_codehigh', 'v2xlg_legcon_sd', 'v2x_partip', 'v2x_partip_codelow', 'v2x_partip_codehigh', 'v2x_partip_sd', 'v2x_cspart', 'v2x_cspart_codelow', 'v2x_cspart_codehigh', 'v2x_cspart_sd', 'v2xdd_dd', 'v2xel_locelec', 'v2xel_locelec_codelow', 'v2xel_locelec_codehigh', 'v2xel_locelec_sd', 'v2xel_regelec', 'v2xel_regelec_codelow', 'v2xel_regelec_codehigh', 'v2xel_regelec_sd', 'v2xdl_delib', 'v2xdl_delib_codelow', 'v2xdl_delib_codehigh', 'v2xdl_delib_sd', 'v2x_egal', 'v2x_egal_codelow', 'v2x_egal_codehigh', 'v2x_egal_sd', 'v2xeg_eqprotec', 'v2xeg_eqprotec_codelow', 'v2xeg_eqprotec_codehigh', 'v2xeg_eqprotec_sd', 'v2xeg_eqaccess', 'v2xeg_eqaccess_codelow', 'v2xeg_eqaccess_codehigh', 'v2xeg_eqaccess_sd', 'v2xeg_eqdr', 'v2xeg_eqdr_codelow', 'v2xeg_eqdr_codehigh', 'v2xeg_eqdr_sd', 'v2eltype_0', 'v2eltype_1', 'v2eltype_2', 'v2eltype_3', 'v2eltype_4', 'v2eltype_5', 'v2eltype_6', 'v2eltype_7', 'v2eltype_8', 'v2eltype_9', 'v2elcomvot', 'v2elfemrst', 'v2elage', 'v2elgvsuflvl', 'v2elsuffrage', 'v2elwestmon', 'v2asuffrage', 'v2fsuffrage', 'v2msuffrage', 'v2eldonate', 'v2eldonate_codelow', 'v2eldonate_codehigh', 'v2eldonate_sd', 'v2eldonate_osp', 'v2eldonate_osp_codelow', 'v2eldonate_osp_codehigh', 'v2eldonate_osp_sd', 'v2eldonate_ord', 'v2eldonate_ord_codelow', 'v2eldonate_ord_codehigh', 'v2eldonate_mean', 'v2eldonate_nr', 'v2elpubfin', 'v2elpubfin_codelow', 'v2elpubfin_codehigh', 'v2elpubfin_sd', 'v2elpubfin_osp', 'v2elpubfin_osp_codelow', 'v2elpubfin_osp_codehigh', 'v2elpubfin_osp_sd', 'v2elpubfin_ord', 'v2elpubfin_ord_codelow', 'v2elpubfin_ord_codehigh', 'v2elpubfin_mean', 'v2elpubfin_nr', 'v2elembaut', 'v2elembaut_codelow', 'v2elembaut_codehigh', 'v2elembaut_sd', 'v2elembaut_osp', 'v2elembaut_osp_codelow', 'v2elembaut_osp_codehigh', 'v2elembaut_osp_sd', 'v2elembaut_ord', 'v2elembaut_ord_codelow', 'v2elembaut_ord_codehigh', 'v2elembaut_mean', 'v2elembaut_nr', 'v2elembcap', 'v2elembcap_codelow', 'v2elembcap_codehigh', 'v2elembcap_sd', 'v2elembcap_osp', 'v2elembcap_osp_codelow', 'v2elembcap_osp_codehigh', 'v2elembcap_osp_sd', 'v2elembcap_ord', 'v2elembcap_ord_codelow', 'v2elembcap_ord_codehigh', 'v2elembcap_mean', 'v2elembcap_nr', 'v2elmulpar', 'v2elmulpar_codelow', 'v2elmulpar_codehigh', 'v2elmulpar_sd', 'v2elmulpar_osp', 'v2elmulpar_osp_codelow', 'v2elmulpar_osp_codehigh', 'v2elmulpar_osp_sd', 'v2elmulpar_ord', 'v2elmulpar_ord_codelow', 'v2elmulpar_ord_codehigh', 'v2elmulpar_mean', 'v2elmulpar_nr', 'v2elrgstry', 'v2elrgstry_codelow', 'v2elrgstry_codehigh', 'v2elrgstry_sd', 'v2elrgstry_osp', 'v2elrgstry_osp_codelow', 'v2elrgstry_osp_codehigh', 'v2elrgstry_osp_sd', 'v2elrgstry_ord', 'v2elrgstry_ord_codelow', 'v2elrgstry_ord_codehigh', 'v2elrgstry_mean', 'v2elrgstry_nr', 'v2elvotbuy', 'v2elvotbuy_codelow', 'v2elvotbuy_codehigh', 'v2elvotbuy_sd', 'v2elvotbuy_osp', 'v2elvotbuy_osp_codelow', 'v2elvotbuy_osp_codehigh', 'v2elvotbuy_osp_sd', 'v2elvotbuy_ord', 'v2elvotbuy_ord_codelow', 'v2elvotbuy_ord_codehigh', 'v2elvotbuy_mean', 'v2elvotbuy_nr', 'v2elirreg', 'v2elirreg_codelow', 'v2elirreg_codehigh', 'v2elirreg_sd', 'v2elirreg_osp', 'v2elirreg_osp_codelow', 'v2elirreg_osp_codehigh', 'v2elirreg_osp_sd', 'v2elirreg_ord', 'v2elirreg_ord_codelow', 'v2elirreg_ord_codehigh', 'v2elirreg_mean', 'v2elirreg_nr', 'v2elintim', 'v2elintim_codelow', 'v2elintim_codehigh', 'v2elintim_sd', 'v2elintim_osp', 'v2elintim_osp_codelow', 'v2elintim_osp_codehigh', 'v2elintim_osp_sd', 'v2elintim_ord', 'v2elintim_ord_codelow', 'v2elintim_ord_codehigh', 'v2elintim_mean', 'v2elintim_nr', 'v2elpeace', 'v2elpeace_codelow', 'v2elpeace_codehigh', 'v2elpeace_sd', 'v2elpeace_osp', 'v2elpeace_osp_codelow', 'v2elpeace_osp_codehigh', 'v2elpeace_osp_sd', 'v2elpeace_ord', 'v2elpeace_ord_codelow', 'v2elpeace_ord_codehigh', 'v2elpeace_mean', 'v2elpeace_nr', 'v2elboycot', 'v2elboycot_codelow', 'v2elboycot_codehigh', 'v2elboycot_sd', 'v2elboycot_osp', 'v2elboycot_osp_codelow', 'v2elboycot_osp_codehigh', 'v2elboycot_osp_sd', 'v2elboycot_ord', 'v2elboycot_ord_codelow', 'v2elboycot_ord_codehigh', 'v2elboycot_mean', 'v2elboycot_nr', 'v2elfrcamp', 'v2elfrcamp_codelow', 'v2elfrcamp_codehigh', 'v2elfrcamp_sd', 'v2elfrcamp_osp', 'v2elfrcamp_osp_codelow', 'v2elfrcamp_osp_codehigh', 'v2elfrcamp_osp_sd', 'v2elfrcamp_ord', 'v2elfrcamp_ord_codelow', 'v2elfrcamp_ord_codehigh', 'v2elfrcamp_mean', 'v2elfrcamp_nr', 'v2elpdcamp', 'v2elpdcamp_codelow', 'v2elpdcamp_codehigh', 'v2elpdcamp_sd', 'v2elpdcamp_osp', 'v2elpdcamp_osp_codelow', 'v2elpdcamp_osp_codehigh', 'v2elpdcamp_osp_sd', 'v2elpdcamp_ord', 'v2elpdcamp_ord_codelow', 'v2elpdcamp_ord_codehigh', 'v2elpdcamp_mean', 'v2elpdcamp_nr', 'v2elpaidig', 'v2elpaidig_codelow', 'v2elpaidig_codehigh', 'v2elpaidig_sd', 'v2elpaidig_osp', 'v2elpaidig_osp_codelow', 'v2elpaidig_osp_codehigh', 'v2elpaidig_osp_sd', 'v2elpaidig_ord', 'v2elpaidig_ord_codelow', 'v2elpaidig_ord_codehigh', 'v2elpaidig_mean', 'v2elpaidig_nr', 'v2elfrfair', 'v2elfrfair_codelow', 'v2elfrfair_codehigh', 'v2elfrfair_sd', 'v2elfrfair_osp', 'v2elfrfair_osp_codelow', 'v2elfrfair_osp_codehigh', 'v2elfrfair_osp_sd', 'v2elfrfair_ord', 'v2elfrfair_ord_codelow', 'v2elfrfair_ord_codehigh', 'v2elfrfair_mean', 'v2elfrfair_nr', 'v2elrstrct', 'v2eldommon', 'v2elintmon', 'v2elmonden', 'v2elmonref', 'v2elaccept', 'v2elaccept_codelow', 'v2elaccept_codehigh', 'v2elaccept_sd', 'v2elaccept_osp', 'v2elaccept_osp_codelow', 'v2elaccept_osp_codehigh', 'v2elaccept_osp_sd', 'v2elaccept_ord', 'v2elaccept_ord_codelow', 'v2elaccept_ord_codehigh', 'v2elaccept_mean', 'v2elaccept_nr', 'v2elasmoff', 'v2elasmoff_codelow', 'v2elasmoff_codehigh', 'v2elasmoff_sd', 'v2elasmoff_osp', 'v2elasmoff_osp_codelow', 'v2elasmoff_osp_codehigh', 'v2elasmoff_osp_sd', 'v2elasmoff_ord', 'v2elasmoff_ord_codelow', 'v2elasmoff_ord_codehigh', 'v2elasmoff_mean', 'v2elasmoff_nr', 'v2elvaptrn', 'v2eltrnout', 'v2lpname', 'v2slpname', 'v2tlpname', 'v2eltvrexo', 'v2elvotlrg', 'v2elvotsml', 'v2elturnhog', 'v2elturnhos', 'v2elrsthos', 'v2elrsthog', 'v2elprescons', 'v2elprescumul', 'v2elthresh', 'v2eltvrig', 'v2ellostsl', 'v2ellostss', 'v2ellovtlg', 'v2ellovtsm', 'v2ellostlg', 'v2elloseat', 'v2ellostsm', 'v2elloelsy', 'v2ellocons', 'v2ellocumul', 'v2elparlel', 'v2elloeldm', 'v2ellovttm', 'v2ellosttm', 'v2ellostts', 'v2ellobaseat', 'v2ellobadis', 'v2elloupdis', 'v2elloreseat', 'v2ellodiseff', 'v2elreggov', 'v2elregnam', 'v2elsrgel', 'v2elrgpwr', 'v2elrgpwr_codelow', 'v2elrgpwr_codehigh', 'v2elrgpwr_sd', 'v2elrgpwr_osp', 'v2elrgpwr_osp_codelow', 'v2elrgpwr_osp_codehigh', 'v2elrgpwr_osp_sd', 'v2elrgpwr_ord', 'v2elrgpwr_ord_codelow', 'v2elrgpwr_ord_codehigh', 'v2elrgpwr_mean', 'v2elrgpwr_nr', 'v2ellocgov', 'v2ellocnam', 'v2ellocelc', 'v2ellocpwr', 'v2ellocpwr_codelow', 'v2ellocpwr_codehigh', 'v2ellocpwr_sd', 'v2ellocpwr_osp', 'v2ellocpwr_osp_codelow', 'v2ellocpwr_osp_codehigh', 'v2ellocpwr_osp_sd', 'v2ellocpwr_ord', 'v2ellocpwr_ord_codelow', 'v2ellocpwr_ord_codehigh', 'v2ellocpwr_mean', 'v2ellocpwr_nr', 'v2elffelr', 'v2elffelr_codelow', 'v2elffelr_codehigh', 'v2elffelr_sd', 'v2elffelr_osp', 'v2elffelr_osp_codelow', 'v2elffelr_osp_codehigh', 'v2elffelr_osp_sd', 'v2elffelr_ord', 'v2elffelr_ord_codelow', 'v2elffelr_ord_codehigh', 'v2elffelr_mean', 'v2elffelr_nr', 'v2elffelrbin', 'v2elffelrbin_codelow', 'v2elffelrbin_codehigh', 'v2elffelrbin_sd', 'v2elffelrbin_osp', 'v2elffelrbin_osp_codelow', 'v2elffelrbin_osp_codehigh', 'v2elffelrbin_osp_sd', 'v2elffelrbin_ord', 'v2elffelrbin_ord_codelow', 'v2elffelrbin_ord_codehigh', 'v2elffelrbin_mean', 'v2elffelrbin_nr', 'v2elsnlsff', 'v2elsnlsff_codelow', 'v2elsnlsff_codehigh', 'v2elsnlsff_sd', 'v2elsnlsff_osp', 'v2elsnlsff_osp_codelow', 'v2elsnlsff_osp_codehigh', 'v2elsnlsff_osp_sd', 'v2elsnlsff_ord', 'v2elsnlsff_ord_codelow', 'v2elsnlsff_ord_codehigh', 'v2elsnlsff_mean', 'v2elsnlsff_nr', 'v2elsnlfc_0', 'v2elsnlfc_1', 'v2elsnlfc_2', 'v2elsnlfc_3', 'v2elsnlfc_4', 'v2elsnlfc_5', 'v2elsnlfc_6', 'v2elsnlfc_7', 'v2elsnlfc_8', 'v2elsnlfc_9', 'v2elsnlfc_10', 'v2elsnlfc_11', 'v2elsnlfc_12', 'v2elsnlfc_13', 'v2elsnlfc_14', 'v2elsnlfc_15', 'v2elsnlfc_16', 'v2elsnlfc_17', 'v2elsnlfc_18', 'v2elsnlfc_19', 'v2elsnlfc_20', 'v2elsnlfc_21', 'v2elsnlfc_nr', 'v2elsnmrfc_0', 'v2elsnmrfc_1', 'v2elsnmrfc_2', 'v2elsnmrfc_3', 'v2elsnmrfc_4', 'v2elsnmrfc_5', 'v2elsnmrfc_6', 'v2elsnmrfc_7', 'v2elsnmrfc_8', 'v2elsnmrfc_9', 'v2elsnmrfc_10', 'v2elsnmrfc_11', 'v2elsnmrfc_12', 'v2elsnmrfc_13', 'v2elsnmrfc_14', 'v2elsnmrfc_15', 'v2elsnmrfc_16', 'v2elsnmrfc_17', 'v2elsnmrfc_18', 'v2elsnmrfc_19', 'v2elsnmrfc_20', 'v2elsnmrfc_21', 'v2elsnmrfc_nr', 'v2psbars', 'v2psbars_codelow', 'v2psbars_codehigh', 'v2psbars_sd', 'v2psbars_osp', 'v2psbars_osp_codelow', 'v2psbars_osp_codehigh', 'v2psbars_osp_sd', 'v2psbars_ord', 'v2psbars_ord_codelow', 'v2psbars_ord_codehigh', 'v2psbars_mean', 'v2psbars_nr', 'v2psparban', 'v2psparban_codelow', 'v2psparban_codehigh', 'v2psparban_sd', 'v2psparban_osp', 'v2psparban_osp_codelow', 'v2psparban_osp_codehigh', 'v2psparban_osp_sd', 'v2psparban_ord', 'v2psparban_ord_codelow', 'v2psparban_ord_codehigh', 'v2psparban_mean', 'v2psparban_nr', 'v2psoppaut', 'v2psoppaut_codelow', 'v2psoppaut_codehigh', 'v2psoppaut_sd', 'v2psoppaut_osp', 'v2psoppaut_osp_codelow', 'v2psoppaut_osp_codehigh', 'v2psoppaut_osp_sd', 'v2psoppaut_ord', 'v2psoppaut_ord_codelow', 'v2psoppaut_ord_codehigh', 'v2psoppaut_mean', 'v2psoppaut_nr', 'v2psorgs', 'v2psorgs_codelow', 'v2psorgs_codehigh', 'v2psorgs_sd', 'v2psorgs_osp', 'v2psorgs_osp_codelow', 'v2psorgs_osp_codehigh', 'v2psorgs_osp_sd', 'v2psorgs_ord', 'v2psorgs_ord_codelow', 'v2psorgs_ord_codehigh', 'v2psorgs_mean', 'v2psorgs_nr', 'v2psprbrch', 'v2psprbrch_codelow', 'v2psprbrch_codehigh', 'v2psprbrch_sd', 'v2psprbrch_osp', 'v2psprbrch_osp_codelow', 'v2psprbrch_osp_codehigh', 'v2psprbrch_osp_sd', 'v2psprbrch_ord', 'v2psprbrch_ord_codelow', 'v2psprbrch_ord_codehigh', 'v2psprbrch_mean', 'v2psprbrch_nr', 'v2psprlnks', 'v2psprlnks_codelow', 'v2psprlnks_codehigh', 'v2psprlnks_sd', 'v2psprlnks_osp', 'v2psprlnks_osp_codelow', 'v2psprlnks_osp_codehigh', 'v2psprlnks_osp_sd', 'v2psprlnks_ord', 'v2psprlnks_ord_codelow', 'v2psprlnks_ord_codehigh', 'v2psprlnks_mean', 'v2psprlnks_nr', 'v2psplats', 'v2psplats_codelow', 'v2psplats_codehigh', 'v2psplats_sd', 'v2psplats_osp', 'v2psplats_osp_codelow', 'v2psplats_osp_codehigh', 'v2psplats_osp_sd', 'v2psplats_ord', 'v2psplats_ord_codelow', 'v2psplats_ord_codehigh', 'v2psplats_mean', 'v2psplats_nr', 'v2pscnslnl', 'v2pscnslnl_codelow', 'v2pscnslnl_codehigh', 'v2pscnslnl_sd', 'v2pscnslnl_osp', 'v2pscnslnl_osp_codelow', 'v2pscnslnl_osp_codehigh', 'v2pscnslnl_osp_sd', 'v2pscnslnl_ord', 'v2pscnslnl_ord_codelow', 'v2pscnslnl_ord_codehigh', 'v2pscnslnl_mean', 'v2pscnslnl_nr', 'v2pscohesv', 'v2pscohesv_codelow', 'v2pscohesv_codehigh', 'v2pscohesv_sd', 'v2pscohesv_osp', 'v2pscohesv_osp_codelow', 'v2pscohesv_osp_codehigh', 'v2pscohesv_osp_sd', 'v2pscohesv_ord', 'v2pscohesv_ord_codelow', 'v2pscohesv_ord_codehigh', 'v2pscohesv_mean', 'v2pscohesv_nr', 'v2pscomprg', 'v2pscomprg_codelow', 'v2pscomprg_codehigh', 'v2pscomprg_sd', 'v2pscomprg_osp', 'v2pscomprg_osp_codelow', 'v2pscomprg_osp_codehigh', 'v2pscomprg_osp_sd', 'v2pscomprg_ord', 'v2pscomprg_ord_codelow', 'v2pscomprg_ord_codehigh', 'v2pscomprg_mean', 'v2pscomprg_nr', 'v2psnatpar', 'v2psnatpar_codelow', 'v2psnatpar_codehigh', 'v2psnatpar_sd', 'v2psnatpar_osp', 'v2psnatpar_osp_codelow', 'v2psnatpar_osp_codehigh', 'v2psnatpar_osp_sd', 'v2psnatpar_ord', 'v2psnatpar_ord_codelow', 'v2psnatpar_ord_codehigh', 'v2psnatpar_mean', 'v2psnatpar_nr', 'v2pssunpar', 'v2pssunpar_codelow', 'v2pssunpar_codehigh', 'v2pssunpar_sd', 'v2pssunpar_osp', 'v2pssunpar_osp_codelow', 'v2pssunpar_osp_codehigh', 'v2pssunpar_osp_sd', 'v2pssunpar_ord', 'v2pssunpar_ord_codelow', 'v2pssunpar_ord_codehigh', 'v2pssunpar_mean', 'v2pssunpar_nr', 'v2psbantar_0', 'v2psbantar_1', 'v2psbantar_2', 'v2psbantar_3', 'v2psbantar_4', 'v2psbantar_5', 'v2psbantar_nr', 'v2ddlexci', 'v2ddsignci', 'v2ddsigpci', 'v2ddsigdci', 'v2ddsiglci', 'v2ddpartci', 'v2ddapprci', 'v2ddadmci', 'v2ddspmci', 'v2ddthreci', 'v2ddlexrf', 'v2ddsignrf', 'v2ddsigprf', 'v2ddsigdrf', 'v2ddsiglrf', 'v2ddpartrf', 'v2ddapprrf', 'v2ddadmrf', 'v2ddspmrf', 'v2ddthrerf', 'v2ddlexor', 'v2ddpartor', 'v2ddappor', 'v2ddadmor', 'v2ddspmor', 'v2ddthreor', 'v2ddlexpl', 'v2ddpartpl', 'v2ddapprpl', 'v2ddadmpl', 'v2ddspmpl', 'v2ddthrepl', 'v2ddyrci', 'v2ddyrrf', 'v2ddyror', 'v2ddyrpl', 'v2ddyrall', 'v2ddcredal', 'v2exnamhos', 'v2extithos', 'v2exremhsp', 'v2exremhsp_codelow', 'v2exremhsp_codehigh', 'v2exremhsp_sd', 'v2exremhsp_osp', 'v2exremhsp_osp_codelow', 'v2exremhsp_osp_codehigh', 'v2exremhsp_osp_sd', 'v2exremhsp_ord', 'v2exremhsp_ord_codelow', 'v2exremhsp_ord_codehigh', 'v2exremhsp_mean', 'v2exremhsp_nr', 'v2exdfdshs', 'v2exdfdshs_codelow', 'v2exdfdshs_codehigh', 'v2exdfdshs_sd', 'v2exdfdshs_osp', 'v2exdfdshs_osp_codelow', 'v2exdfdshs_osp_codehigh', 'v2exdfdshs_osp_sd', 'v2exdfdshs_ord', 'v2exdfdshs_ord_codelow', 'v2exdfdshs_ord_codehigh', 'v2exdfdshs_mean', 'v2exdfdshs_nr', 'v2exdfcbhs', 'v2exdfcbhs_codelow', 'v2exdfcbhs_codehigh', 'v2exdfcbhs_sd', 'v2exdfcbhs_osp', 'v2exdfcbhs_osp_codelow', 'v2exdfcbhs_osp_codehigh', 'v2exdfcbhs_osp_sd', 'v2exdfcbhs_ord', 'v2exdfcbhs_ord_codelow', 'v2exdfcbhs_ord_codehigh', 'v2exdfcbhs_mean', 'v2exdfcbhs_nr', 'v2exdfvths', 'v2exdfvths_codelow', 'v2exdfvths_codehigh', 'v2exdfvths_sd', 'v2exdfvths_osp', 'v2exdfvths_osp_codelow', 'v2exdfvths_osp_codehigh', 'v2exdfvths_osp_sd', 'v2exdfvths_ord', 'v2exdfvths_ord_codelow', 'v2exdfvths_ord_codehigh', 'v2exdfvths_mean', 'v2exdfvths_nr', 'v2exdfdmhs', 'v2exdfdmhs_codelow', 'v2exdfdmhs_codehigh', 'v2exdfdmhs_sd', 'v2exdfdmhs_osp', 'v2exdfdmhs_osp_codelow', 'v2exdfdmhs_osp_codehigh', 'v2exdfdmhs_osp_sd', 'v2exdfdmhs_ord', 'v2exdfdmhs_ord_codelow', 'v2exdfdmhs_ord_codehigh', 'v2exdfdmhs_mean', 'v2exdfdmhs_nr', 'v2exdfpphs', 'v2exdfpphs_codelow', 'v2exdfpphs_codehigh', 'v2exdfpphs_sd', 'v2exdfpphs_osp', 'v2exdfpphs_osp_codelow', 'v2exdfpphs_osp_codehigh', 'v2exdfpphs_osp_sd', 'v2exdfpphs_ord', 'v2exdfpphs_ord_codelow', 'v2exdfpphs_ord_codehigh', 'v2exdfpphs_mean', 'v2exdfpphs_nr', 'v2exhoshog', 'v2exagehos', 'v2exaphos', 'v2ex_elechos', 'v2exfemhos', 'v2exfxtmhs', 'v2expathhs', 'v2exdeathos', 'v2exparhos', 'v2exctlhs_0', 'v2exctlhs_1', 'v2exctlhs_2', 'v2exctlhs_3', 'v2exctlhs_4', 'v2exctlhs_5', 'v2exctlhs_6', 'v2exctlhs_7', 'v2exctlhs_nr', 'v2exrmhsol_0', 'v2exrmhsol_1', 'v2exrmhsol_2', 'v2exrmhsol_3', 'v2exrmhsol_4', 'v2exrmhsol_5', 'v2exrmhsol_6', 'v2exrmhsol_7', 'v2exrmhsol_nr', 'v2exdfcbhs_rec', 'v2exdfcbhs_rec_codelow', 'v2exdfcbhs_rec_codehigh', 'v2exdfcbhs_rec_sd', 'v2exdfcbhs_rec_osp', 'v2exdfcbhs_rec_osp_codelow', 'v2exdfcbhs_rec_osp_codehigh', 'v2exdfcbhs_rec_osp_sd', 'v2exdfcbhs_rec_ord', 'v2exdfcbhs_rec_ord_codelow', 'v2exdfcbhs_rec_ord_codehigh', 'v2exdfcbhs_rec_mean', 'v2exdfcbhs_rec_nr', 'v2exnamhog', 'v2extithog', 'v2exremhog', 'v2exremhog_codelow', 'v2exremhog_codehigh', 'v2exremhog_sd', 'v2exremhog_osp', 'v2exremhog_osp_codelow', 'v2exremhog_osp_codehigh', 'v2exremhog_osp_sd', 'v2exremhog_ord', 'v2exremhog_ord_codelow', 'v2exremhog_ord_codehigh', 'v2exremhog_mean', 'v2exremhog_nr', 'v2exdjdshg', 'v2exdjdshg_codelow', 'v2exdjdshg_codehigh', 'v2exdjdshg_sd', 'v2exdjdshg_osp', 'v2exdjdshg_osp_codelow', 'v2exdjdshg_osp_codehigh', 'v2exdjdshg_osp_sd', 'v2exdjdshg_ord', 'v2exdjdshg_ord_codelow', 'v2exdjdshg_ord_codehigh', 'v2exdjdshg_mean', 'v2exdjdshg_nr', 'v2exdjcbhg', 'v2exdjcbhg_codelow', 'v2exdjcbhg_codehigh', 'v2exdjcbhg_sd', 'v2exdjcbhg_osp', 'v2exdjcbhg_osp_codelow', 'v2exdjcbhg_osp_codehigh', 'v2exdjcbhg_osp_sd', 'v2exdjcbhg_ord', 'v2exdjcbhg_ord_codelow', 'v2exdjcbhg_ord_codehigh', 'v2exdjcbhg_mean', 'v2exdjcbhg_nr', 'v2exdfdshg', 'v2exdfdshg_codelow', 'v2exdfdshg_codehigh', 'v2exdfdshg_sd', 'v2exdfdshg_osp', 'v2exdfdshg_osp_codelow', 'v2exdfdshg_osp_codehigh', 'v2exdfdshg_osp_sd', 'v2exdfdshg_ord', 'v2exdfdshg_ord_codelow', 'v2exdfdshg_ord_codehigh', 'v2exdfdshg_mean', 'v2exdfdshg_nr', 'v2exdfvthg', 'v2exdfvthg_codelow', 'v2exdfvthg_codehigh', 'v2exdfvthg_sd', 'v2exdfvthg_osp', 'v2exdfvthg_osp_codelow', 'v2exdfvthg_osp_codehigh', 'v2exdfvthg_osp_sd', 'v2exdfvthg_ord', 'v2exdfvthg_ord_codelow', 'v2exdfvthg_ord_codehigh', 'v2exdfvthg_mean', 'v2exdfvthg_nr', 'v2exdfpphg', 'v2exdfpphg_codelow', 'v2exdfpphg_codehigh', 'v2exdfpphg_sd', 'v2exdfpphg_osp', 'v2exdfpphg_osp_codelow', 'v2exdfpphg_osp_codehigh', 'v2exdfpphg_osp_sd', 'v2exdfpphg_ord', 'v2exdfpphg_ord_codelow', 'v2exdfpphg_ord_codehigh', 'v2exdfpphg_mean', 'v2exdfpphg_nr', 'v2exagehog', 'v2exaphogp', 'v2ex_elechog', 'v2exfemhog', 'v2exfxtmhg', 'v2ex_hogw', 'v2ex_hosconhog', 'v2expathhg', 'v2expothog', 'v2exdeathog', 'v2exctlhg_0', 'v2exctlhg_1', 'v2exctlhg_2', 'v2exctlhg_3', 'v2exctlhg_4', 'v2exctlhg_5', 'v2exctlhg_6', 'v2exctlhg_7', 'v2exctlhg_8', 'v2exctlhg_nr', 'v2exrmhgnp_0', 'v2exrmhgnp_1', 'v2exrmhgnp_2', 'v2exrmhgnp_3', 'v2exrmhgnp_4', 'v2exrmhgnp_5', 'v2exrmhgnp_6', 'v2exrmhgnp_7', 'v2exrmhgnp_8', 'v2exrmhgnp_nr', 'v2exrescon', 'v2exrescon_codelow', 'v2exrescon_codehigh', 'v2exrescon_sd', 'v2exrescon_osp', 'v2exrescon_osp_codelow', 'v2exrescon_osp_codehigh', 'v2exrescon_osp_sd', 'v2exrescon_ord', 'v2exrescon_ord_codelow', 'v2exrescon_ord_codehigh', 'v2exrescon_mean', 'v2exrescon_nr', 'v2exbribe', 'v2exbribe_codelow', 'v2exbribe_codehigh', 'v2exbribe_sd', 'v2exbribe_osp', 'v2exbribe_osp_codelow', 'v2exbribe_osp_codehigh', 'v2exbribe_osp_sd', 'v2exbribe_ord', 'v2exbribe_ord_codelow', 'v2exbribe_ord_codehigh', 'v2exbribe_mean', 'v2exbribe_nr', 'v2exembez', 'v2exembez_codelow', 'v2exembez_codehigh', 'v2exembez_sd', 'v2exembez_osp', 'v2exembez_osp_codelow', 'v2exembez_osp_codehigh', 'v2exembez_osp_sd', 'v2exembez_ord', 'v2exembez_ord_codelow', 'v2exembez_ord_codehigh', 'v2exembez_mean', 'v2exembez_nr', 'v2excrptps', 'v2excrptps_codelow', 'v2excrptps_codehigh', 'v2excrptps_sd', 'v2excrptps_osp', 'v2excrptps_osp_codelow', 'v2excrptps_osp_codehigh', 'v2excrptps_osp_sd', 'v2excrptps_ord', 'v2excrptps_ord_codelow', 'v2excrptps_ord_codehigh', 'v2excrptps_mean', 'v2excrptps_nr', 'v2exthftps', 'v2exthftps_codelow', 'v2exthftps_codehigh', 'v2exthftps_sd', 'v2exthftps_osp', 'v2exthftps_osp_codelow', 'v2exthftps_osp_codehigh', 'v2exthftps_osp_sd', 'v2exthftps_ord', 'v2exthftps_ord_codelow', 'v2exthftps_ord_codehigh', 'v2exthftps_mean', 'v2exthftps_nr', 'v2exapup', 'v2exapupap', 'v2reginfo', 'v2regendtype', 'v2regint', 'v2regidnr', 'v2regdur', 'v2regimpgroup', 'v2regimpgroup_nr', 'v2regsupgroupssize', 'v2regsupgroupssize_codelow', 'v2regsupgroupssize_codehigh', 'v2regsupgroupssize_sd', 'v2regsupgroupssize_osp', 'v2regsupgroupssize_osp_codelow', 'v2regsupgrou

Important Columns from VDEM are: 
V-Dem-CY-Full+Others-v16.csv
monadic:

v2x_cspart
(Civil Society Participation)

v2x_clphy
(Physical Integrity Rights)

v2x_freexp_altinf
(Freedom of Expression & Alternative Info)

v2xcl_rol
(Rule of Law Index)

v2x_execorr
(Executive Corruption Index)

v2x_corr
(Political Corruption Index)

v2xlg_legcon
(Legislative Constraints on the Executive)

v2x_jucon
(Judicial Constraints on the Executive)

v2x_regime
(Regimes of the World)

v2x_egaldem
(Egalitarian Democracy Index)

v2x_delibdem
(Deliberative Democracy Index)

v2x_partipdem
(Participatory Democracy Index)

v2x_libdem
(Liberal Democracy Index)

v2x_polyarchy
(Electoral Democracy Index) (Must-Have)

COWcode

ountry_name

year

country_text_id

# Polity 5 Data

In [5]:
polity_folder_path = Path(r"../data/raw/PolityV")
polity_file_path = polity_folder_path /"CSPCoupsAnnualv2021.xls"

In [6]:
polity_excel = pd.ExcelFile(polity_file_path)
print(polity_excel.sheet_names)

['Sheet1', 'Sheet2', 'Sheet3']

In [7]:
polity_df1 = pd.read_excel(polity_excel, sheet_name='Sheet1')
print(polity_df1.columns.tolist())

['ccode', 'scode', 'country', 'year', 'scoup1', 'atcoup2', 'pcoup3', 'apcoup4', 'agcoup', 'foroutex', 'reboutex', 'assassex', 'resignex']

‼️‼️Columns?

Sheet2 and Sheet3 are empty

In [8]:
p5v_file_path = polity_folder_path/ "p5v2018.sav"

In [9]:
p5v_df, meta = pyreadstat.read_sav(p5v_file_path)
print(p5v_df.columns.tolist())

['p5', 'cyear', 'ccode', 'scode', 'country', 'year', 'flag', 'fragment', 'democ', 'autoc', 'polity', 'polity2', 'durable', 'xrreg', 'xrcomp', 'xropen', 'xconst', 'parreg', 'parcomp', 'exrec', 'exconst', 'polcomp', 'prior', 'emonth', 'eday', 'eyear', 'eprec', 'interim', 'bmonth', 'bday', 'byear', 'bprec', 'post', 'change', 'd5', 'sf', 'regtrans']

‼️‼️Important feature in p5v_df
Monadic Features:

year, 

country, 

ccode, 

DEMOC, 

AUTOC, 

Polity2, 

Transition and 

interregnum

Flag Variables (-66,-77,-88)

# SPRI

In [10]:
spri_folder = Path(r"../data/raw/SPRI")
spri_financial_value_file_path = spri_folder / "Financial Values of Arms Exports 1994_2022.xlsx"

In [11]:
spri_financial_value_excel = pd.ExcelFile(spri_financial_value_file_path) #excel file object
print(spri_financial_value_excel.sheet_names) #list of sheet names

['Local Currency', 'Current US', 'Constant US']

This file not requried for me.

In [12]:
spri_milex_file_path = spri_folder / "SIPRI_Milex_data_1949_2025_v1.2.xlsx"

In [13]:
spri_milex_excel = pd.ExcelFile(spri_milex_file_path)
print(spri_milex_excel.sheet_names)

['Front page', 'Regional totals', 'Local currency financial years', 'Local currency calendar years', 'Constant (2024) US$', 'Current US$', 'Share of GDP', 'Per capita', 'Share of Govt. spending', 'Footnotes']

Important Sheets:

1. Constant (2024) US$

2. Share of GDP

3. Share of Govt. spending

In [14]:
spri_milex_df1 = pd.read_excel(spri_milex_excel, sheet_name="Current US$", skiprows=5) #true data starts at row 6
spri_milex_df1.head(10)

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,10217.0817,10073.364021,9583.724288,10303.600575,9708.27744,9112.461105,9145.810174,18263.967968,21811.242555,25438.789692
4,Libya,‡§¶16,xxx,xxx,...,...,...,...,...,...,...,...,...,...,...,...,...,1212.526035,1572.965617,...,...
5,Morocco,§17,xxx,xxx,xxx,xxx,xxx,xxx,xxx,23.714286,...,3327.237293,3492.074842,3696.571638,3694.594868,4829.507988,5325.480901,4993.737492,5189.111532,5516.970249,6330.727244
6,Tunisia,NaN,xxx,xxx,xxx,xxx,xxx,xxx,xxx,3.714286,...,987.005168,856.691156,843.6768,998.72775,1152.698062,1231.004127,1146.732826,1207.275849,1315.226311,1484.859114
7,sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Angola,§‖1,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,2764.054937,3062.872914,1982.252745,1469.786382,992.496819,973.942252,1623.340729,1247.846345,924.256506,1459.150446
9,Benin,§,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,79.626313,116.933111,90.260725,68.117853,71.803344,97.451778,109.994281,149.05623,167.317204,216.913737

I can remove notes

Countries are listed under Regions and Sub-regions. I'll remove those regions and subregios.

In [15]:
spri_milex_df2 = pd.read_excel(spri_milex_excel, sheet_name="Share of GDP", skiprows =5) #true data starts at row 6
spri_milex_df2.head(10)

,Country,Notes,1949,1950,1951,1952,1953,1954,1955,1956,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,0.056527,0.053071,0.049299,0.05327,0.058861,0.0489,0.040575,0.073904,0.079715,0.088306
4,Libya,‡§¶16,xxx,xxx,...,...,...,...,...,...,...,...,...,...,...,...,...,0.028038,0.035725,...,...
5,Morocco,§17,xxx,xxx,xxx,xxx,xxx,xxx,xxx,0.011807,...,0.029821,0.029459,0.029029,0.028658,0.039797,0.037498,0.038049,0.035528,0.034351,0.035431
6,Tunisia,NaN,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,...,0.02225,0.020318,0.019764,0.023833,0.027128,0.026151,0.025512,0.025049,0.024989,0.02495
7,sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Angola,§‖1,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,0.027333,0.02508,0.019558,0.017679,0.018104,0.013932,0.014327,0.014298,0.010339,0.013968
9,Benin,§,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,...,0.006736,0.009206,0.006329,0.004733,0.004588,0.005509,0.006321,0.007576,0.007788,0.008901

I can remove Notes

In [16]:
spri_milex_df3 = pd.read_excel(spri_milex_excel, sheet_name="Share of Govt. spending", skiprows=7) #true data starts at row 6
spri_milex_df3.head(10)

,Country,Notes,Reporting year,1988,1989,1990,1991,1992,1993,1994,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algeria,§4,NaN,...,...,0.057841,0.040441,0.069904,0.070861,0.093684,...,0.152039,0.146409,0.135999,0.143587,0.156941,0.15025,0.124128,0.19741,0.220313,0.245708
4,Libya,‡§¶16,NaN,...,...,...,...,...,...,...,...,...,...,...,...,...,...,0.045085,0.054661,...,...
5,Morocco,§17,NaN,...,...,0.145002,0.158037,0.15113,0.158109,0.162983,...,0.104448,0.105925,0.104896,0.104736,0.116552,0.120899,0.11285,0.111141,0.103951,0.102801
6,Tunisia,NaN,NaN,...,...,...,0.063269,0.063291,0.061916,0.064018,...,0.08176,0.070733,0.068902,0.080702,0.078555,0.079197,0.07046,0.069666,0.073342,0.075357
7,sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Angola,§‖1,NaN,...,...,...,...,...,...,...,...,0.124,0.104141,0.095039,0.085236,0.074624,0.066798,0.058413,0.059104,0.043573,0.059155
9,Benin,§,NaN,...,0.104652,0.092393,...,...,...,...,...,0.043661,0.051764,0.038229,0.032416,0.024056,0.027745,0.031821,0.039517,0.043142,0.048193

I can remove Notes and Reporting Year

# UCDP

In [17]:
ucdp_folder = Path(r"../data/raw/UCDP")
ucdp_file_path = ucdp_folder / "UcdpPrioConflict_v26_1.csv"

In [18]:
ucdp_df = pd.read_csv(ucdp_file_path, nrows=3)
print(ucdp_df.columns.tolist())

['conflict_id', 'location', 'side_a', 'side_a_id', 'side_a_2nd', 'side_b', 'side_b_id', 'side_b_2nd', 'incompatibility', 'territory_name', 'year', 'intensity_level', 'cumulative_intensity', 'type_of_conflict', 'start_date', 'start_prec', 'start_date2', 'start_prec2', 'ep_end', 'ep_end_date', 'ep_end_prec', 'gwno_a', 'gwno_a_2nd', 'gwno_b', 'gwno_b_2nd', 'gwno_loc', 'region', 'version']

important feature: 
### Dyadic:
side_a, 

side_a_id, 

sida_a_2nd, 

side_b, 

side_b_id, 

side_b_2nd, 

intensity_level, 

incompatibility, 

territory_name, 

type_of_conflict,

 start_date, 
 
 gwno_a, 
 
 gwno_a_2nd, 
 
 gwno_b, 
 
 gwno_b_2nd, 
 
 region.

### Missing Data:
dyad_id, conflict_id, year, cumulative_intensity.

# WDI

In [19]:
wdi_folder_path = Path(r"../data/raw/WDI_CSV")
wdi_country_file_path = wdi_folder_path/ "WDICountry.csv"
wdi_csv_file_path = wdi_folder_path/ "WDICSV.csv"

In [20]:
wdi_country_df = pd.read_csv(wdi_country_file_path, nrows=3)
print(wdi_country_df.columns.tolist())

['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data']

Important features:

Country Code, 

Long Name, 

Income Group

In [21]:
wdi_csv_df = pd.read_csv(wdi_csv_file_path, nrows=3)
print(wdi_csv_df.columns.tolist())

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

Features:

Country Name, 

Country Code,

 Indicator Name, 
 
 Indicator Code,
 
  Year (2000, 2021)

### Most important World Bank's indicator codes:

NY.ADJ.NNTY.KD.ZG

NY.ADJ.NNTY.KD

NY.ADJ.NNTY.PC.KD.ZG

NY.ADJ.NNTY.PC.KD

NY.ADJ.AEDU.GN.ZS

TX.VAL.AGRI.ZS.UN

MS.MIL.TOTL.TF.ZS

MS.MIL.TOTL.P1

MS.MIL.XPRT.KD

MS.MIL.MPRT.KD

FB.BNK.CAPA.ZS

FD.RES.LIQU.AS.ZS

FB.AST.NPER.ZS

VC.BTL.DETH

GC.DOD.TOTL.GD.ZS

GC.DOD.TOTL.CNAG.PRD.CREL.MT

EG.IMP.CONS.ZS

NY.EXP.CAPM.KN

NE.EXP.GNFS.ZS

NE.EXP.GNFS.KD.ZG

NE.EXP.GNFS.KD

NE.IMP.GNFS.KD

DT.DOD.DECT.GN.ZS

AG.PRD.FOOD.XD

TX.VAL.FOOD.ZS.UN

TM.VAL.FOOD.ZS.UN

BN.KLT.DINV.CD

BX.KLT.DINV.WD.GD.ZS

BM.KLT.DINV.WD.GD.ZS

EG.USE.COMM.FO.ZS

TX.VAL.FUEL.ZS.UN

TM.VAL.FUEL.ZS.UN

NY.GDP.MKTP.KD

NY.GDP.MKTP.KD.ZG

NY.GDP.PCAP.KD

NY.GDP.PCAP.KD.ZG

SI.POV.GINI

NY.GNP.MKTP.KD

NY.GNP.MKTP.KD.ZG

FP.CPI.TOTL.ZG

NY.GDP.DEFL.KD.ZG

NY.GDP.DEFL.KD.ZG.AD

MS.MIL.XPND.GD.ZS

MS.MIL.XPND.ZS

SP.POP.TOTL.FE.INSP.POP.TOTL.MA.IN

SP.POP.TOTL

GB.XPD.RSDV.GD.ZS

SP.POP.SCIE.RD.P6

TM.TAX.MRCH.SM.AR.ZS

TM.TAX.MRCH.SM.FN.ZS

FI.RES.TOTL.DT.ZS

FI.RES.TOTL.CDFI.RES.XGLD.CD

NE.TRD.GNFS.ZS

# SystemicPeace

In [22]:
syspeace_folder_path = Path(r"../data/raw/SystemicPeace")
MEPV_file_path = syspeace_folder_path / "MEPV2012ex.xls"

In [23]:
MEPV_excel = pd.ExcelFile(MEPV_file_path)
print(MEPV_excel.sheet_names)

['MEPV2012n']

only one sheel : MEPV2012n

In [25]:
MEPV_df = pd.read_excel(MEPV_excel)
print(MEPV_df.columns.tolist())

['SCODE', 'CCODE', 'COUNTRY', 'YEAR', 'IND', 'INTIND', 'INTVIOL', 'INTWAR', 'CIVVIOL', 'CIVWAR', 'ETHVIOL', 'ETHWAR', 'INTTOT', 'CIVTOT', 'ACTOTAL', 'nBORDER', 'TOTINT', 'TOTCIV', 'TOTALAC', 'nINT', 'nCIV', 'nAC', 'REGION', 'nREGION', 'REGINT', 'REGCIV', 'REGAC', 'nRINT', 'nRCIV', 'nRAC', 'NCIVLIST', 'NINTLIST', 'NACLIST']

Important Features:

MEPV2012ex.xls

Monadic

nRAC, 

REGCIV, 

REGAC, 

nAC, 

TOTCIV, 

TOTALAC, 

INTTOT, 

CIVTOT,

 ACTOTAL, 
 
 IND, 
 
 YEAR, 
 
 SCODE

# Cultural Difference

In [27]:
cd_folder_path = Path(r"../data/raw/Capdist&Cultural_difference")
capdist_file_path = cd_folder_path / "capdist.csv"
cul_dist_file_path = cd_folder_path / "cultural_distance_PSW2024.csv"

In [28]:
capdist_df = pd.read_csv(capdist_file_path, nrows=3)
print(capdist_df.columns.tolist())

['numa', 'ida', 'numb', 'idb', 'kmdist', 'midist']

Features

numa

ida

numb

idb

kmdist

midist

In [29]:
cult_dist_df = pd.read_csv(cul_dist_file_path, nrows=3)
print(cult_dist_df.columns.tolist())

['year', 'countrycode_1', 'countrycode_2', 'cultdist', 'cultdist_std', 'n_questions']

Features

Year

countrycode_1

countrycode_2

cultdist